# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p2p.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tp2p.proto\x12\x03p2p\"9\n\x0eGetFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x15\n\rpeer_username\x18\x02 \x01(\t\"\"\n\x0fGetFileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2A\n\tP2PServer\x12\x34\n\x07GetFile\x12\x13.p2p.GetFileRequest\x1a\x14.p2p.GetFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETFILEREQUEST']._serialized_start=18
  _globals['_GETFILEREQUEST']._serialized_end=75
  _globals['_GETFILERESPONSE']._serialized_start=77
  _globals['_GETFILERESPONSE']._serialized_end=111
  _globals['_P2PSERVER']._serialized_start=113
  _globals['_P2PSERVER']._serialized_end=178
# @@protoc_insertion_point(module_scope)
